name: Setup Python Environment
description: Setup Python and install dependencies with Poetry
on:
  workflow_call:
    inputs:
      python-version:
        default: '3.7'
        description: Python version number to use.
        required: true
        type: string
runs:
  using: composite
  steps:
  - name: Install system dependencies
    shell: bash
    run: |
      sudo apt update
      sudo apt install libegl1-mesa -y

  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup python ${{ inputs.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}

  - name: Setup Poetry
    uses: Gr1N/setup-poetry@v7

  - name: Install package
    shell: bash
    run: |
      poetry install
