# Platform: win-64
# Create with: conda env create --file environment.yml

# This environment file is intended to initialize this repo for running on Google Colab.
# Because of this, preference is given to install all the packages required by Colab using pip
# (since this is the easiest way to do it in Colab). The other packages can be installed using
# Conda.

name: boiling-learning
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  # base dependencies
  - pip
  - python==3.7.*

  # linters
  - flake8
  - mypy
  - pylint
  - yapf

  # packages
  - nidaqmx-python
  - funcy>=1.15
  - more-itertools
  - scikit-learn
  - decorator
  - h5py
  - modin[ray]
  - parse
  - frozendict
  - pims
  - scipy
  - scikit-image
  - opencv
  - numpy
  - matplotlib
  - bokeh
  - bidict
  - pint
  - sortedcontainers
  - zict
  - zlib
  - typing-extensions
  - setuptools==52.0.0


  - jupyter

  - pip:
    - -r file:requirements.txt
