[tool.isort]
profile = "black"
known_first_party = ["boiling_learning"]
multi_line_output = 3
line_length = 79

[tool.black]
include = '\.pyi?$'
line-length = 79
skip-string-normalization = true
target-version = ['py37']

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "0.3.3"
version_files = [
	"VERSION",
]
