[project]
name = "boiling-learning"
version = "0.20.38"
description = "Deep learning models for phase-change quantification and classification."
authors = [
    {name = "Ruan Comelli", email = "ruancomelli@gmail.com"}
]
dependencies = [
    "aioredis<2.0.0,>=1.3.1",
    "av>=8.0.0,<9.0.0",
    "bokeh<3.0.0,>=2.4.2",
    "decorator<6.0.0,>=5.1.1",
    "frozendict<2.0,>=1.2",
    "funcy<2.0,>=1.17",
    "gspread<6.0.0,>=5.1.1",
    "imageio==2.4.1",
    "ipywidgets<8.0.0,>=7.6.5",
    "matplotlib<4.0.0,>=3.5.1",
    "more-itertools>=8.11.0",
    "nidaqmx<1.0.0,>=0.5.7",
    "numpy<1.22.0,>=1.19.5",
    "oauth2client<5.0.0,>=4.1.3",
    "opencv-python<5.0.0.0,>=4.5.5.62",
    "parse<2.0.0,>=1.19.0",
    "PIMS<1.0,>=0.5",
    "Pint<1.0,>=0.18",
    "scikit-image<1.0.0,>=0.19.1",
    "scikit-learn<2.0.0,>=1.0.2",
    "scipy<2.0.0,>=1.7.3",
    "tensorflow-addons==0.16.1",
    "tinydb<5.0.0,>=4.5.2",
    "typing-extensions>=4.2.0",
    "tensorflow<2.9.0,>=2.8.0",
    "slicerator<2.0.0,>=1.0.0",
    "albumentations<2.0.0,>=1.1.0",
    "classes<1.0.0,>=0.4.0",
    "tinydb-smartcache<3.0.0,>=2.0.0",
    "iteround<2.0.0,>=1.0.3",
    "pyqtgraph==0.12.3",
    "PyQt6<7.0.0,>=6.2.2",
    "modin[all]>=0.12.1",
    "loguru>=0.6.0",
    "h5py>=3.7.0",
    "hdf5plugin>=3.3.0",
    "mypy>=0.960",
]

requires-python = ">=3.7.12,<3.10"
license = {text = "MIT"}
readme = "README.md"
keywords = ["python", "machine-learning", "deep-learning", "tensorflow", "phase-change"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Financial and Insurance Industry",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Physics"
]

[project.urls]
homepage = ""
"Bug Tracker" = "https://github.com/ruancomelli/boiling-learning/issues"
repository = "https://github.com/ruancomelli/boiling-learning"
documentation = "https://github.com/ruancomelli/boiling_learning/blob/main/README.md"

[project.optional-dependencies]

[project.entry-points.tox]
pdm = "tox_pdm.plugin"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
test = [
    "pytest>=6.2.5",
    "coverage>=5.5",
    "tox>=3.24.4",
    "tox-asdf>=0.1.0",
    "tox-gh-actions>=2.9.0",
    "tox-pdm>=0.3.2"
]
lint = [
    "autoflake>=1.4",
    "black>=22.3.0",
    "flake8>=3.9.2",
    "isort[requirements_deprecated_finder]>=5.10.1",
    "unimport>=0.9.2",
    "pylint>=2.12.2",
    "vulture>=2.3"]
ci = [
    "commitizen==2.20.1",
    "pre-commit>=2.15.0"
]
build = [
    "pip>=22.0.3",
    "wheel>=0.37.1",
    "setuptools>=60.7.1"
]
types = [
    "mypy>=0.940",
    "types-decorator>=5.1.3",
    "types-frozendict>=2.0.4",
    "types-PyYAML>=6.0.3",
]

[tool.isort]
profile = "black"
known_first_party = ["boiling_learning"]
multi_line_output = 3
line_length = 99
float_to_top = true
remove_redundant_aliases = true

[tool.unimport]
gitignore = true
ignore_init = true
include_star_import = true
remove = true
requirements = true

[tool.black]
include = '\.py|\.pyi|\.ipynb$'
line-length = 99
skip-string-normalization = true
target-version = ['py37']

[tool.mypy]
mypy_path = "./typings"
follow_imports = "normal"
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
plugins = [
    "classes.contrib.mypy.classes_plugin",
	"numpy.typing.mypy_plugin",
	"tinydb.mypy_plugin",
]

[tool.commitizen]
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "0.20.38"
version_files = ["pyproject.toml:version"]
