name: Automerge Pull Request
on:
  pull_request:
    types:
    - labeled
    - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
    - name: automerge
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_LABELS: automerge,!merge-conflict
        MERGE_METHOD: squash
        MERGE_DELETE_BRANCH: true
