name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update dependencies
      uses: pdm-project/update-deps-action@v1
      with:
        commit-message: 'build(deps): update dependencies'
        pr-title: Automatic update of dependencies
